services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $frontendBlocks: !tagged_locator { tag: forkcms.frontend.block }

  ForkCMS\Modules\Pages\Domain\:
    resource: '../Domain/*'

  ForkCMS\Modules\Pages\Backend\:
    resource: '../Backend/*'

  ForkCMS\Modules\Pages\Frontend\:
    resource: '../Frontend/*'

  ForkCMS\Modules\Pages\Controller\:
    resource: '../Controller/*'
    public: true

  ForkCMS\Modules\Pages\DependencyInjection\PagesRouteLoader:

  ForkCMS\Modules\Frontend\Domain\Block\BlockRouterInterface: '@ForkCMS\Modules\Pages\Domain\Page\PageRouter'
