vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        files:
            # uri_prefix: /media
            upload_destination: media_library.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            # inject_on_load: true
