parameters:
    media_library.image_extensions: [gif, jpeg, jpg, png, tiff, svg]
    media_library.image_mime_types: [image/gif, image/jpeg, image/pjpeg, image/png, image/tiff, image/x-tiff, image/svg, image/svg+xml]

    media_library.file_extensions: [doc, docx, pdf]
    media_library.file_mime_types: [application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/pdf]

    media_library.movie_extensions: [avi, mp4]
    media_library.movie_mime_types: [video/x-msvideo, video/mp4, application/mp4]

    media_library.audio_extensions: [mp3, mp4a, wav]
    media_library.audio_mime_types: [audio/mpeg3, video/mpeg, video/x-mpeg, audio/x-mpeg-3, audio/mp4, audio/wav, audio/x-wav, audio/mpeg]

services:
  _defaults:
    autowire: true
    autoconfigure: true

  ForkCMS\Modules\MediaLibrary\Domain\:
    resource: '../Domain/*'

  ForkCMS\Modules\MediaLibrary\Backend\:
    resource: '../Backend/*'

  ForkCMS\Modules\MediaLibrary\Frontend\:
    resource: '../Frontend/*'
