doctrine:
  dbal:
    types:
      datetime_immutable: ForkCMS\Core\Domain\Doctrine\UTCDateTimeImmutableDBALType
      datetime_mutable: ForkCMS\Core\Domain\Doctrine\UTCDateTimeMutableDBALType
      time_immutable: ForkCMS\Core\Domain\Doctrine\UTCTimeImmutableDBALType
      time_mutable: ForkCMS\Core\Domain\Doctrine\UTCTimeMutableDBALType

